name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gen-lang-client-0736387453

      - name: Upload DAG to Composer
        run: |
          gcloud composer environments storage dags import \
            --environment loblaws \
            --location us-central1 \
            --source train_dag.py

      - name: Trigger DAG
        run: |
          gcloud composer environments run loblaws \
            --location us-central1 \
            dags trigger -- Main
